spring.application.name=relay

spring.datasource.url=jdbc:mysql://localhost:3306/relay
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PSWD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mock.world.url=http://localhost:9210

relay.webhook.secret=${YOUR_SECRET}